services:
  server:
    build: .
    image: ubuntu-os
    working_dir: /usr/local/src
    networks:
      - os
    volumes:
      - type: bind
        source: .
        target: /usr/local/src
  client:
    build: .
    image: ubuntu-os
    working_dir: /usr/local/src
    networks:
      - os
    volumes:
      - type: bind
        source: .
        target: /usr/local/src
  remoteclient:
    build: .
    image: ubuntu-os
    working_dir: /usr/local/src
    network_mode: host
    volumes:
      - type: bind
        source: .
        target: /usr/local/src
networks:
  os:
